### ISSUE TITLE
Aceita dicas para o projeto?

### ISSUE THREAD

**Issue by luan0ap** [jowslive/listasimples#1]
Olá! Gostaria de saber se aceitaria dicas para melhorar ainda mais a performance e semântica da aplicação? 

Parece uma pergunta besta, mas tem muitos devs que não gostam muito de receberem feedbacks de seus projetos, ainda mais pessoais. Curto colaborar com a galera se quiser algumas dicas só da um toque nessa issue aqui o/

**Comment by jowslive** [comment]
Clarooo que aceito ! Sinta-se livre para compartilhar qualquer dica o/
