### ISSUE TITLE
[DICAS] - Algumas sugestões :)

### ISSUE THREAD

**Issue by luan0ap** [jowslive/listasimples#2]
Opá! Então como eu havia mencionado em outra issue, vou deixar uns alguns pontos interessantes que podem ser vistos no projeto:

Falando um pouco do HTML:

-  Daria para deixar tudo separado por exemplo js em um lugar html e css eu outro, tipo tentar evitar o CSS inline e o JS. Existem muitos dos "por quês" não usar eles inline no próprio stackoverflow você encontra muito coisa, como: [Why inline JavaScript is bad?](https://stackoverflow.com/questions/19002690/why-inline-javascript-is-bad) e [Is it really a bad practice to use inline styles in HTML?](https://www.quora.com/Is-it-really-a-bad-practice-to-use-inline-styles-in-HTML)

- Um outro ponto legal de se comentar é sobre o uso dos ID's como seletores CSS, sei que muitas pessoas ainda usam, porém você pode deixar os id para uso exclusivo de TAG's que precisam dele como a `<label>`, deixe os estilos por responsabilidade das classes :)

- E como chamar no JS então se não tem ID's? Bem você pode optar por usar do nosso querido atributo `data-*`, por exemplo no código seria algo assim: 

No HTML
```
<section data-js="section"></section>
```

E no JS
```
const $section = document.querySelector('[data-js="section"]')
```
- E também sobre os nomes das classes ficaria confuso colocando naquele estilo boostrap da vida, com `center` e tals, pow já pensou em conferir algumas convenções de nomes? Tem várias eu particularmente prefiro o [RSCSS](https://willianjusten.com.br/falando-sobre-rscss/), mas tem também o [BEM](http://getbem.com/introduction), [Atomic](https://github.com/nemophrost/atomic-css), [CSSinJS](http://cssinjs.org/) e assim vai, escolha um, você vai gostar :)

Tenho alguns outros pontos que gostaria de comentar, mas estou meio sem tempo e pra não ficar um textão chato :v então fico por aqui mesmo, tudo de bom mano sucesso!!!

**Comment by jowslive** [comment]
Esse comentário me ajudou muito na época mas esqueci de responder, muito obrigado!
